export enum CounterType {
  INCREMENT = 'INCREMENT',
  DECREASE = 'DECREASE',
}

export enum ViewType {
  VIEWCHANGE = 'VIEWCHANGE',
  USER_NAME = 'USER_NAME',
  CHECK_BOX = 'CHECK_BOX',
  AMOUNT = 'AMOUNT',
  PRICE = 'PRICE',
  CALC = 'CALC',
  USER_VIEW = 'USER_VIEW',
  ORDER_VIEW = 'ORDER_VIEW',
}
